default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  timeout: 5000
  username: root
  password: mk mysql


development:
  <<: *default
  database: sample_app

test:
  <<: *default
  database: sample_app_test
